name: .NET Core Unit Tests

on:
  push:
    branches:
      - "main"

jobs:
   
        
  Checkout:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout  
      uses: actions/checkout@v1

  Build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1

    - name: Build
      run: dotnet build --configuration Release
      
  Test:

    runs-on: ubuntu-latest

    steps:

    - name: Test
      run: dotnet test --logger "trx;LogFileName=test-results.trx" || true

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true
